services:

  frontend:
    build: ./frontend
    container_name: chronicle-frontend

    ports:
      - "3010:80"

    depends_on:
      - backend

    restart: unless-stopped

  backend:
    build: ./backend

    container_name: chronicle-backend

    restart: unless-stopped

    volumes:
      - ./data:/app/data